export const translations: Record<string, Record<string, string>> = {
  en: {
    app_name: "Laborbook",
    total_staff: "Staff",
    today_present: "Present",
    today_absent: "Absent",
    today_unmarked: "Unmarked",
    monthly_overview: "Monthly Overview",
    total_workers: "Total Workers",
    total_advance: "Total Advance",
    net_payable: "Net Balance",
    add_staff: "Add Staff",
    add_staff_title: "Add New Staff / Labor",
    cash_book: "Cash Book",
    settings: "Settings",
    search_staff: "Search staff name or phone...",
    search_transactions: "Search notes or amount...",
    worker_details: "Worker Details",
    daily_attendance: "Daily Attendance",
    overtime: "Overtime",
    advance: "Advance",
    balance: "Balance",
    present: "Present",
    absent: "Absent",
    half_day: "Half Day",
    double: "Double (P+P)",
    present_half: "Present + 1/2",
    unmarked: "Unmarked",
    open_report: "Open Report",
    whatsapp_share: "Share Slip",
    cash_in: "Cash In",
    cash_out: "Cash Out",
    enter_amount: "Enter Amount",
    select_date: "Select Date",
    payment_mode: "Payment Mode",
    cash: "Cash",
    online: "Online",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    name: "Staff Name",
    phone_number: "Phone Number",
    daily_wage: "Daily Wage / Monthly Salary",
    salary_type: "Salary Type",
    daily: "Daily",
    monthly: "Monthly",
    overview: "Overview",
    total_present: "Total Present",
    total_absent: "Total Absent",
    over_time: "Over time",
    pdf_reports: "PDF Reports Hub",
    download_csv: "Export Master CSV Backup",
    restore_csv: "Import Master CSV Backup",
    clear_data: "Reset All Data",
    business_name: "Business / Site Name",
    user_mobile: "Registered Mobile",
    user_email: "Account Email",
    language: "Language",
    language_en: "English",
    language_hi: "हिंदी (Hindi)",
  },
  hi: {
    app_name: "लेबर बुक",
    total_staff: "कुल मजदूर",
    today_present: "उपस्थित",
    today_absent: "अनुपस्थित",
    today_unmarked: "चिह्नित नहीं",
    monthly_overview: "मासिक विवरण",
    total_workers: "कुल मजदूर",
    total_advance: "कुल एडवांस",
    net_payable: "शुद्ध बकाया",
    add_staff: "मजदूर जोड़ें",
    add_staff_title: "नया मजदूर जोड़ें",
    cash_book: "रोकड़ बही (Cash Book)",
    settings: "सेटिंग्स",
    search_staff: "नाम या फोन से खोजें...",
    search_transactions: "लेनदेन खोजें...",
    worker_details: "मजदूर विवरण",
    daily_attendance: "दैनिक हाजिरी",
    overtime: "ओवरटाइम",
    advance: "एडवांस",
    balance: "बैलेंस",
    present: "उपस्थित (P)",
    absent: "अनुपस्थित (A)",
    half_day: "आधा दिन (H)",
    double: "डबल (P+P)",
    present_half: "P + आधा",
    unmarked: "खाली",
    open_report: "रिपोर्ट खोलें",
    whatsapp_share: "स्लिप शेयर करें",
    cash_in: "जमा (Cash In)",
    cash_out: "खर्च (Cash Out)",
    enter_amount: "रकम दर्ज करें",
    select_date: "तारीख चुनें",
    payment_mode: "भुगतान का प्रकार",
    cash: "नकद (Cash)",
    online: "ऑनलाइन (Online)",
    save: "सुरक्षित करें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "बदलें",
    name: "मजदूर का नाम",
    phone_number: "मोबाइल नंबर",
    daily_wage: "दैनिक मजदूरी / वेतन",
    salary_type: "वेतन प्रकार",
    daily: "दैनिक (Daily)",
    monthly: "मासिक (Monthly)",
    overview: "विवरण",
    total_present: "कुल उपस्थित",
    total_absent: "कुल अनुपस्थित",
    over_time: "ओवरटाइम",
    pdf_reports: "पीडीएफ रिपोर्ट हब",
    download_csv: "बैकअप सीएसवी डाउनलोड",
    restore_csv: "बैकअप सीएसवी रीस्टोर",
    clear_data: "डेटा रीसेट करें",
    business_name: "व्यापार / साइट का नाम",
    user_mobile: "मोबाइल नंबर",
    user_email: "ईमेल आईडी",
    language: "भाषा",
    language_en: "English",
    language_hi: "हिंदी (Hindi)",
  }
};

export function t(key: string, lang: string = "en"): string {
  const selectedLang = lang === "hi" ? "hi" : "en";
  return translations[selectedLang]?.[key] || translations["en"]?.[key] || key;
}
